### PR TITLE
Fixed order of packages in composer.json

### PR DESCRIPTION
**Pull request by michalbundyra**
Correct order of packages in require(-dev) section is as follows:
  - php version
  - ext-* - php extensions in alphabetical order
  - packages in alphabetical order

### CODE REVIEW

**Comment by weierophinney** [comment]
This will get overwritten every time we change a requirement due to `config.sort_packages: true`. :wink:

While I definitely prefer having the PHP version and extensions earlier, using that configuration ensures that all other packages are in alphabetical order, ensuring that they can be found easily when scanning the file. I'd prefer automation over manually ensuring that.

**Comment by michalbundyra** [comment]
@weierophinney Actually not. the order I've provided is the order from composer automation - I've tested it on the latest composer version 1.5.2.

**Comment by michalbundyra** [comment]
@weierophinney I've checked composer source and it seems to be there for a long while, please see:
https://github.com/composer/composer/pull/3872
I've checked the latest version and it is still there, so definitely it is as I've described in PR description.

**Comment by weierophinney** [comment]
Thanks, @webimpress

**Pull request merged**
