### PR TITLE
fix wrong package name in composer install command

### PR DESCRIPTION
**Pull request by Repkit**
Provide a narrative description of what you are trying to accomplish:

- [ ] Are you fixing a bug?
  - [ ] Detail how the bug is invoked currently.
  - [ ] Detail the original, incorrect behavior.
  - [ ] Detail the new, expected behavior.
  - [ ] Base your feature on the `master` branch, and submit against that branch.
  - [ ] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

- [ ] Are you creating a new feature?
  - [ ] Why is the new feature needed? What purpose does it serve?
  - [ ] How will users use the new feature?
  - [ ] Base your feature on the `develop` branch, and submit against that branch.
  - [ ] Add only one feature per pull request; split multiple features over multiple pull requests
  - [ ] Add tests for the new feature.
  - [ ] Add documentation for the new feature.
  - [ ] Add a `CHANGELOG.md` entry for the new feature.

- [x] Is this related to quality assurance?
  

- [x] Is this related to documentation?

### CODE REVIEW

**Comment by akrabat** [comment]
Fixes one part of #43

**Comment by akrabat** [comment]
@Repkit Thanks. 

Do you fancy fixing the links to issues and source too as part of this PR?

**Comment by froschdesign** [comment]
@Repkit 
Good catch, but wrong file. The `index.html` is no longer used.

**Comment by froschdesign** [comment]
@akrabat 
Please wait! Wrong file!

@Repkit 
We must update the MkDocs configuration: https://github.com/zendframework/zend-problem-details/blob/master/mkdocs.yml#L12

**Comment by akrabat** [comment]
There should probably be link to the documentation on how to write docs…

**Comment by froschdesign** [comment]
@akrabat 
You are right, but at the moment there is no description for that, because the documentation template and build process is still under development.

**Pull request closed without merging**
