### PR TITLE
Added support for `http-interop/http-middleware` 0.5.0 (no BC Break)

### PR DESCRIPTION
**Pull request by michalbundyra**
https://github.com/http-interop/http-middleware/tree/0.5.0

### CODE REVIEW

**Comment by belgattitude** [comment]
Cool, wait for expressive support ;)

**Comment by weierophinney** [comment]
We cannot do this until zend-stratigility and zend-expressive support it. This work is in progress (@xtreamwayz has begun it), but we do not yet have a planned release date.

I'll merge this when that happens.

**Comment by michalbundyra** [comment]
@weierophinney In commit 9022519 I've changed approach and it could be merged **WITHOUT** BC break. I've created separate repository which handle all versions of http-interop/http-middleware. I've started preparing PR to other libraries, and it should be ready shorty. Please check the library [`webimpress/http-middleware-compatibility`](https://github.com/webimpress/http-middleware-compatibility) and changes in this PR.

**Comment by michalbundyra** [comment]
@weierophinney Rebased, conflict resolved.

**Comment by weierophinney** [comment]
Thanks, @webimpress

**Pull request merged**
